### ISSUE TITLE
error in cmake

### ISSUE THREAD

**Issue by anishpdoshi** [heal-research/operon#24]
Hello,
I get the following error when running
```
cmake .. -DCMAKE_TOOLCHAIN_FILE=/Users/apdoshi/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release  -DBUILD_PYBIND=OF -DUSE_OPENLIBM=ON -DUSE_SINGLE_PRECISION=ON -DCERES_TINY_SOLVER=ON
```

```
-- Running vcpkg install
Error: while loading aria-csv:
The port directory (/Users/apdoshi/vcpkg/ports/aria-csv) does not exist
Error: failed to load port from /Users/apdoshi/vcpkg/ports/aria-csv
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
-- Running vcpkg install - failed
CMake Error at /Users/apdoshi/vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
  vcpkg install failed.  See logs for more information:
  /Users/apdoshi/operon/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.22.1/share/cmake/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:8 (project)
  ```

**Comment by foolnotion** [comment]
Hi,

It seems that vcpkg failes to parse or understand the `vcpkg.json` manifest file.
Could you please post the full `vcpkg-manifest-install.log`?

Alternatively, could you make sure that you use the latest version of vcpkg and that you run it from the operon root folder?
```
cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=/Users/apdoshi/vcpkg/scripts/buildsystems/vcpkg.cmake`
```

We are using the official vcpkg guide for packaging: https://vcpkg.io/en/docs/examples/packaging-github-repos.html

Thanks

**Comment by anishpdoshi** [comment]
Thanks. The full manifest install log is just this:
```
Error: while loading aria-csv:
The port directory (/Users/apdoshi/vcpkg/ports/aria-csv) does not exist
Error: failed to load port from /Users/apdoshi/vcpkg/ports/aria-csv
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

I am on the latest vcpkg and reran boostratp-vckpgs.sh, but ports/aria-csv still does not exist unfortunately

**Comment by foolnotion** [comment]
That's because `aria-csv` is not in the official ports, we provide it locally under the `operon/ports` folder.
Normally vcpkg should read the `vcpkg.json` manifest file and figure this out.
However, it does seem like vcpkg is more fragile than it looks. 

Some things to try:

- setting up the `VCPKG_OVERLAY_PORTS` env variable as per instructions [here](https://github.com/microsoft/vcpkg/blob/master/docs/users/config-environment.md#vcpkg_overlay_ports)
- passing `--preset build-windows-vcpkg` (or whichever fits your system) to CMake (use `cmake --list-presets` or have a look at the `CMakePresets.json` file
- passing `-DVCPKG_OVERLAY_PORTS=./ports` to CMake

**Comment by anishpdoshi** [comment]
I see. Passing in the `-DVCPKG_OVERLAY_PORTS` option worked, and it built. Thanks!
