### ISSUE TITLE
Custom cost function

### ISSUE THREAD

**Issue by arita37** [heal-research/operon#26]
Hello,

just checking if it is possible to use a custom
cost function like

def mycost(expr_str):

     cost = myfun(eval(expr_str))
     return cost

Thnks

**Comment by foolnotion** [comment]
Hi,

Yes, it is possible. With the C++ library, you can construct a `UserDefinedEvaluator` with a lambda, see [here](https://github.com/heal-research/operon/blob/master/include/operon/operators/evaluator.hpp#L211) for an example.

With the python bindings, you need to define a custom function and pass it to the `UserDefinedEvaluator`. Consider the  [operon-bindings.py](https://github.com/heal-research/pyoperon/blob/cpp20/example/operon-bindings.py) example. The following changes will work:
```diff
diff --git a/example/operon-bindings.py b/example/operon-bindings.py
index 100a4e4..b3f3ce5 100644
--- a/example/operon-bindings.py
+++ b/example/operon-bindings.py
@@ -74,10 +74,14 @@ mutation.Add(mut_replace, 1)
 crossover_internal_probability = 0.9 # probability to pick an internal node as a cut point
 crossover      = Operon.SubtreeCrossover(crossover_internal_probability, maxD, maxL)
 
+def custom_eval(rng, ind):
+    return [ ind.Genotype.Length ]
+
 # define fitness evaluation
 interpreter    = Operon.Interpreter() # tree interpreter
 error_metric   = Operon.R2()          # use the coefficient of determination as fitness
-evaluator      = Operon.Evaluator(problem, interpreter, error_metric, True) # initialize evaluator, use linear scaling = True
+#evaluator      = Operon.Evaluator(problem, interpreter, error_metric, True) # initialize evaluator, use linear scaling = True
+evaluator      = Operon.UserDefinedEvaluator(problem, custom_eval)
 evaluator.Budget = 1000 * 1000             # computational budget
 evaluator.LocalOptimizationIterations = 0  # number of local optimization iterations (coefficient tuning using gradient descent)
 ```

Note that this will most likely incur a performance cost due to crossing the python/C++ boundary. If the cost function is expensive enough it might not matter.

I hope this answers your question.
