### ISSUE TITLE
ModuleNotFoundError: No module named 'operon'

### ISSUE THREAD

**Issue by lacava** [heal-research/operon#7]
can't seem to find the module installed anywhere after running a successful install. Here's my setup: 

```
# Installing operon
export CC=gcc-9
export CXX=gcc-9
# Dependencies 
# - TBB - installed via conda
# - Eigen- installed via conda
# - Ceres- installed via conda
# - {fmt}- installed via conda

git clone https://github.com/heal-research/operon
cd operon
# fix version
git checkout a45dd32

# run cmake
mkdir build; cd build; 
cmake .. -DCMAKE_BUILD_TYPE=Release  -DBUILD_PYBIND=ON -DUSE_OPENLIBM=ON -DUSE_SINGLE_PRECISION=ON -DCERES_TINY_SOLVER=ON

#install
make VERBOSE=1


python -c "from operon.sklearn import SymbolicRegressor"
```

I do see operon shared and static objects in the `build/` folder: 

```
ls build
buildinfo.hpp  CMakeCache.txt  CMakeFiles  cmake_install.cmake  _deps  liboperon.a  Makefile  _operon.cpython-39-x86_64-linux-gnu.so
```

installing operon is now part of CI in our [regression-benchmarks](https://github.com/EpistasisLab/regression-benchmark/) project. If you have time maybe you can help update the script to get the build working on [dev](https://github.com/EpistasisLab/regression-benchmark/pull/13). 

this is the install script: https://github.com/EpistasisLab/regression-benchmark/blob/dev/experiment/methods/src/operon_install.sh

**Comment by foolnotion** [comment]
Thanks for the report. That's because the module you see in the `build` folder is an internal module (that's why it's called `_operon`) that binds the methods from the C++ library almost 1:1. The internal module is wrapped by a pure python module `operon` which additionally provides the sklearn estimator.

Normally, you would provide an install prefix with `-DCMAKE_INSTALL_PREFIX=/path/to/module` and then run `make install` when the build is done. `/path/to/module` should be in the `PYTHONPATH` so python can pick it up.

I can update the install script but I would need to know where you want it installed.

**Comment by lacava** [comment]
Operon should end up in `$CONDA_PREFIX/lib/python3.9/site-packages`. I just tried providing this as an argument to -DCMAKE_INSTALL_PREFIX with no luck. I also tried creating a `test_dir` in the operon directory and specifying that, but no files were copied there. I do see the line "-- Python bindings will be installed in `/path/to/operon/test_dir`" during Cmake build, so maybe it is failing silently.

Could be nice to have the python module install as a python package using a minimal `setup.py` script and a call to `python setup.py install`.

**Comment by foolnotion** [comment]
This install script works on my ubuntu machine. It seems that CMake is able to detect the correct library path, so I'd recommend omitting `CMAKE_INSTALL_PREFIX` option so that we don't hardcode the python version.

The module import failure was caused by a name conflict, the file `regression-benchmark/experiment/methods/operon.py` should be renamed to something else like `OperonRegressor.py`.

```bash
# Installing operon
export CC=gcc-9
export CXX=gcc-9
# Dependencies 
# - TBB - installed via conda
# - Eigen- installed via conda
# - Ceres- installed via conda
# - {fmt}- installed via conda

git clone https://github.com/heal-research/operon
cd operon
git checkout 79617d76c97838d91293cff5d4e4fda7230b904b
# run cmake
mkdir build; cd build; 
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_PYBIND=ON -DUSE_OPENLIBM=ON -DUSE_SINGLE_PRECISION=ON -DCERES_TINY_SOLVER=ON

# build
make VERBOSE=1 -j pyoperon

# install
make install
```

After configuring and installing and renaming the regressor, I was actually able to run a small experiment:
```bash
time python evaluate_model.py -ml OperonRegressor Poly-10.csv -seed 1234 -results_path ./results/
```

**Comment by lacava** [comment]
ah ok. Adding `make VERBOSE=1 -j pyoperon; make install` worked like a charm. and i've fixed the name conflict. Would be good to get this in the documentation. Thank you!

**Comment by foolnotion** [comment]
Thanks! Just one last thing: it's maybe better to not fix the revision number in the install script, (at least not right now) since there are still some minor issues in the sklearn wrapper that need to be ironed out.
